services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: naruto-db
    env_file:
      - src/main/resources/variaveis.env
    ports:
      - "27017:27017"
    volumes:
      - naruto_dados:/data/db

volumes:
  naruto_dados:




