services:
  postgres:
    image: postgres
    container_name: naruto-db
    env_file:
      - src/main/resources/variaveis.env
    ports:
      - 5432:5432
    volumes:
      - C:/Users/lisleny.silva/Documents/volumes:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file: src/main/resources/variaveis.env
    ports:
      - "5050:80"
    depends_on:
      - postgres

  flyway:
    image: flyway/flyway:latest
    container_name: flyway
    depends_on:
       postgres:
         condition: service_healthy
    env_file:
       - src/main/resources/variaveis.env
    volumes:
      - /c/Users/lisleny.silva/Documents/crud-naruto/src/main/resources/migration:/flyway/sql



volumes:
  naruto_dados:
    external: true




