#JDBC

spring:
  application:
   name: naruto
  datasource:
   url: jdbc:postgresql://localhost:5432/naruto-db
   username: naruto
   password: ninjutsu

#JPA/Hibernate

  jpa:
   hibernate:
    ddl-auto: none
   properties:
    hibernate:
     dialect: org.hibernate.dialect.PostgreSQLDialect
   show-sql: true


#Flyway

  flyway:
   enabled: true
   locations: classpath:/migration
   baseline-on-migrate: true


